Repository datalad/datalad-crawler, pull requests merged in 2022-10, with the labels that each got.

#127 Set action step outputs via $GITHUB_OUTPUT
  .github/workflows/release.yml
Labels: internal

#128 Update GitHub Actions action versions
  .github/dependabot.yml
  .github/workflows/release.yml
Labels: internal

#126 Guard usage of the legacy method `meta_aggregate`, add datalad-deprecated into tests dependencies
  datalad_crawler/nodes/annex.py
  datalad_crawler/pipelines/gh.py
  setup.py
Labels: release, internal

#129 Fix metadata import and dependency on datalad-deprecated
  datalad_crawler/pipelines/tests/test_openfmri.py
  setup.py
Labels: patch, release, dependencies
